# Практика 1. Знакомство с основными библиотеками Python

На этом занятии мы познакомимся с основными библиотеками, которые понадобятся нам при изучении машинного обучения.

Работа будет происходить в jupyterNootebooks. Это удобный инструмент для интерактивного запуска кода по частям. 

Для работы с ноутбуками можно воспользоваться средствами [GoolgleColaboratory](https://colab.research.google.com/?hl=ru) или запускать их локально.

Нам понадобятся следующие библиотеки:

- Работа с данными:
    - [numpy](https://numpy.org/doc/stable/user/index.html) 
        - Библиотека для работы с многомерными массивами
        - Использует статическую типизацию
        - Позволяет эффективно выполнять операции с матрицами
    - [pandas](https://pandas.pydata.org/docs/user_guide/index.html#user-guide)
        - Частично повторяет синтаксис SQL
        - Обычно используется для работы с табличными данными в формате .csv
        - Включает базовые возможности для предобработки данных
    - [sci-kit-learn](https://scikit-learn.org/stable/user_guide.html)
        - Библиотека, включающая в себя множество реализованный алгоритмов машинного обучения
    - [scipy](https://docs.scipy.org/doc/scipy/tutorial/index.html#user-guide)
        - Библиотека, включающая в себя методы статистического анализа данных и анализа временных рядов
    - и другие
- Библиотеки для визуализации
    - [matplotlib](https://matplotlib.org/stable/users/index)
        - Основная библиотека для отображения графиков различных видов
    - [seaborn](https://seaborn.pydata.org/examples/index.html)
        - Надстройка над matplotlib с готовыми шаблонами для разных видов графиков
    - [plotly](https://plotly.com/python/)
        - Библиотека для отображения отображения графиков с большей интерактивностью

## Библиотека numpy

Основным преимуществом библиотеки numpy является её эффективность. Скорее всего, любой ваш цикл for можно заменить на простую операцию над матрицами в numpy и ускорить работу в разы.

In [1]:
import numpy as np

### Способы создания массивов

- Преобразование списка в массив
- Генерация с использованием специальных функций
- Чтение с диска

<h4>Преобразование списка в массив</h4>

In [2]:
my_list = list(range(0,16))
array = np.array(my_list) # преобразование списка в массив
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
array = np.array(my_list, dtype=np.float64) # Создаём список из элементов Double (float64)
array

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [4]:
array = np.array([[2,3],[4,5]]) # создание матрицы из списка списков 
array

array([[2, 3],
       [4, 5]])

<h4>Специальные функции</h4>

[`arange`](https://numpy.org/doc/stable/reference/generated/numpy.arange.html)

Подобно методу range создаёт значения в диапазоне [start, end) с шагом step. Но range и np.arange сильно отличаются: arange создаёт обычный numpy массив, а range создаёт генератор последовательности значений, не происходит выделения памяти под все значения.

In [5]:
array = np.arange(0, 10, 2) # start, stop, step
array

array([0, 2, 4, 6, 8])

In [6]:
x = np.arange(-1, 1, 0.1) # В отличии от range ещё и может работать с числами с плавающей точкой
x

array([-1.00000000e+00, -9.00000000e-01, -8.00000000e-01, -7.00000000e-01,
       -6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -2.22044605e-16,  1.00000000e-01,
        2.00000000e-01,  3.00000000e-01,  4.00000000e-01,  5.00000000e-01,
        6.00000000e-01,  7.00000000e-01,  8.00000000e-01,  9.00000000e-01])

[`linspace`](https://numpy.org/doc/stable/reference/generated/numpy.linspace.html)

Создаёт массив значений, равномерно распределённых на заданном отрезке.

In [7]:
x = np.linspace(0, 1, 7) # создаёт массив из 7 значений, равномерно расположенных на отрезке [0,1]
x

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

[`zeros`](https://numpy.org/doc/stable/reference/generated/numpy.zeros.html)

Создаёт матрицу, запоненную нулями.

In [8]:
x = np.zeros((2,3,4))
x

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

[`ones`](https://numpy.org/doc/stable/reference/generated/numpy.ones.html)

Создаёт матрицу, заполненную единицами.

In [9]:
x = np.ones((3,1,4))
x

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

[`diag`](https://numpy.org/doc/stable/reference/generated/numpy.diag.html)

Создаёт диагональную матрицу.

In [10]:
x = np.diag(np.arange(5))
x

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [11]:
x = np.diag(np.ones(8))
x

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

[`copy`](https://numpy.org/doc/stable/reference/generated/numpy.copy.html)

Создаёт глубокую копию массива, то есть выделяет память под массив такого же размера и копирует значения.

In [12]:
x = np.arange(5)
y = x
z = x.copy()
x[2]=10
print(f"x = {x}")
print(f"y = {y}")
print(f"z = {z}")

x = [ 0  1 10  3  4]
y = [ 0  1 10  3  4]
z = [0 1 2 3 4]

### Размерность матрицы

*ndim* - количество размерностьей матрицы, *shape* - размерность матрицы.

In [13]:
x = np.ones((4,5,8))
print(f"Размерность массива — {x.shape}, количество размерностей — {x.ndim}")

Размерность массива — (4, 5, 8), количество размерностей — 3

[`reshape`](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html#numpy-reshape)

Позволяет изменять размерность матрицы.

In [14]:
x = np.arange(0, 6)
x = x.reshape((2, 3))
x

array([[0, 1, 2],
       [3, 4, 5]])

Также часто нам будет требоваться генерировать случайные числа. Это можно сделать с помощью модуля `numpy.random`:

In [15]:
# Величины из нормального распределения:
np.random.normal(loc=0,scale=1,size=(5,5))

array([[ 0.5616603 ,  0.53116962,  0.1824832 ,  0.01939206, -1.30350956],
       [-0.42456545, -0.59540682,  0.88778873,  0.06691819,  0.67979829],
       [ 0.29656806, -0.51217284,  1.18700111, -1.36310194, -0.34409741],
       [ 0.76388427, -0.95988335,  0.03498029,  1.44475338, -0.70550098],
       [ 0.06509682,  0.26218305,  1.96745428,  1.51017007,  1.0568126 ]])

In [16]:
# Величины из равномерного распределения:
np.random.uniform(-1,1,size=(5,5))

array([[ 0.57960924, -0.61196368,  0.6862396 ,  0.3667613 , -0.18773928],
       [ 0.27864902,  0.67294859, -0.93615079, -0.35266713, -0.65091197],
       [-0.04201605, -0.25570417, -0.60930532,  0.58201122,  0.72509262],
       [-0.97225664,  0.55949434,  0.11341997,  0.25897626, -0.17160778],
       [ 0.97545737,  0.66283502, -0.15831671, -0.75791593,  0.53312897]])

In [17]:
# Случайные целые числа::
np.random.randint(0,100,size=(5,5))

array([[34, 28, 56, 11, 90],
       [55, 64,  0, 72, 16],
       [51,  5, 42, 74, 39],
       [79,  2, 52, 73, 55],
       [46, 69, 76, 34,  0]], dtype=int32)

В модуле `numpy.random` есть и много других распределений.

In [18]:
print(np.random.__all__)

['beta', 'binomial', 'bytes', 'chisquare', 'choice', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'standard_normal', 'standard_t', 'triangular', 'uniform', 'vonmises', 'wald', 'weibull', 'zipf', 'Generator', 'RandomState', 'SeedSequence', 'MT19937', 'Philox', 'PCG64', 'PCG64DXSM', 'SFC64', 'default_rng', 'BitGenerator']

### Индексация

В NumPy работает привычная индексация Python, включая использование отрицательных индексов и срезов (slices).

In [19]:
array = np.arange(6)
print(array) # весь массив
print(array[0]) # первый элемент
print(array[-1]) # Последний элемент
print(array[1:-1]) # срез всех элементов массива без первого и последнего
print(array[1:-1:2]) # срез всех элементов массива без первого и последнего с шагом 2
print(array[::-1]) # срез массива в обратном порядке

[0 1 2 3 4 5]
0
5
[1 2 3 4]
[1 3]
[5 4 3 2 1 0]

<b>Замечание:</b> Индексы и срезы в многомерных массивах не нужно разделять квадратными скобками, 
т.е. вместо <b>matrix[i][j]</b> нужно использовать <b>matrix[i, j]</b>

<b>Замечание:</b> Срезы в NumPy создают view ("вид"), а не копии данных, поэтому при изменении среза изменится и изначальный массив.

В качестве индексов можно использовать списки

In [20]:
array = np.arange(6).reshape((2,3))
print(array)
array[((0, 1, 1), (0, 1, 2))] 
# Получим элементы с индексами (0,0) (1,1) (1,2)

[[0 1 2]
 [3 4 5]]

array([0, 4, 5])

Или можно воспользоваться маской.

In [21]:
print(np.array([[True, False, False], [True, False, True]]))
array[np.array([[True, False, False], [True, False, True]])]

[[ True False False]
 [ True False  True]]

array([0, 3, 5])

Можно по маске изменить значения в массиве:

In [22]:
array[np.array([[True, False, False], [True, False, True]])]  = 0
array

array([[0, 1, 2],
       [0, 4, 0]])

In [23]:
array[np.array([[True, False, False], [True, False, True]])]  = np.arange(5,8)
array

array([[5, 1, 2],
       [6, 4, 7]])

### Операции с матрицами

В NumPy можно применять привычные нам операции прямо к матрицам.

`x + 2` будет означать, что 2 прибавляется ко всем элементам матрицы.

In [24]:
x = np.arange(10).reshape(2,5)
x = x + 10
x

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [25]:
x % 3

array([[1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1]])

In [26]:
print(x)
x[x % 2==0] *= 2
print(x)

[[10 11 12 13 14]
 [15 16 17 18 19]]
[[20 11 24 13 28]
 [15 32 17 36 19]]

Операции в NumPy можно производить непосредственно над векторами одинаковой размерности без использования циклов

In [27]:
_l = np.linspace(5, 1, 5)
x = np.linspace(1, 5, 5)
print(x)
print(_l)
print(x - _l)
print(x - 2 * _l)
print(x * _l)
print(x / _l)

[1. 2. 3. 4. 5.]
[5. 4. 3. 2. 1.]
[-4. -2.  0.  2.  4.]
[-9. -6. -3.  0.  3.]
[5. 8. 9. 8. 5.]
[0.2 0.5 1.  2.  5. ]

### Расширение размерности

[Broadcasting](https://numpy.org/doc/stable/user/basics.broadcasting.html) позволяет производить операции над массивами разных, но всё-же согласованных размерностей.

![Imgur](https://i.imgur.com/tE3ZCWG.gif)

In [28]:
2 * np.arange(1, 4)

array([2, 4, 6])

Для того, чтобы numpy смог автоматически согласовать размерности, необходимо чтобы размерности либо совпадали либо имели единичный размер.

Прибавить строчку к матрице можно. То есть 1-мерный массив по умолчанию считается вектором-строкой:

In [29]:
a = np.arange(12).reshape(3,4)
print(a.shape)
b = np.arange(4)
print(b.shape)
a + b

(3, 4)
(4,)

array([[ 0,  2,  4,  6],
       [ 4,  6,  8, 10],
       [ 8, 10, 12, 14]])

А вот строчку к столбцам - нет.

In [30]:
a = np.arange(12).reshape(3,4)
print(a.shape)
b = np.arange(3)
print(b.shape)
try:
    a + b
except Exception as e:
    print(e)

(3, 4)
(3,)
operands could not be broadcast together with shapes (3,4) (3,)

Для этого есть трюк с фиктивным расширением размерности. Используя структуру `matrix[np.newaxis, :]` или `matrix[None,:]` мы вектор размерности (n) преобразуем к размерности (1, n). Причём перевыделения памяти не происходит, создаётся view с заданной размерностью:

In [31]:
a = np.arange(12).reshape(3,4)
print(a.shape)
b = np.arange(3)
print(b.shape)
print(b[:,np.newaxis].shape)
a + b[:,np.newaxis]

(3, 4)
(3,)
(3, 1)

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

Записи `matrix[np.newaxis, :]` или `matrix[None,:]` делают одно и то же, но запись с None короче и универсальнее, в других библиотеках, предоставляющих инструменты для работы с матрицами функционал такой-же.

In [32]:
a = np.arange(12).reshape(3,4)
print(a.shape)
b = np.arange(3)
print(b.shape)
print(b[:,None].shape)
a + b[:,None]

(3, 4)
(3,)
(3, 1)

array([[ 0,  1,  2,  3],
       [ 5,  6,  7,  8],
       [10, 11, 12, 13]])

Допустим мы хотим получит попарные произведения каждых значений из двух массивов разного размера. То есть хотим получить что-то такое: $c_{ij}=a_i*b_j,\forall i,j$. Можно написать цикл по $i$ и $j$, а можно воспользоваться трюком с расширением размерности:

In [33]:
a = np.arange(1, 5)
b = np.arange(1, 4)
a[:, None] * b[None, :]

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

Библиотека numpy также поддерживает матричные произведения

Сделать матричное произведение можно следующими способами:
- `np.dot(a,b)`
- `a.dot(b)`
- `a @ b`

Все варианты делают одно и то же действие.

In [34]:
a = np.array([[-1,2],[2,1]])
b = np.array([[3,4],[4,5]])

print(f"a={a}")
print(f"b={b}")
print(f"np.dot(a, b)=\n{np.dot(a,b)}")
print(f"a.dot(b)=\n{a.dot(b)}")
print(f"a @ b=\n{a @ b}")

a=[[-1  2]
 [ 2  1]]
b=[[3 4]
 [4 5]]
np.dot(a, b)=
[[ 5  6]
 [10 13]]
a.dot(b)=
[[ 5  6]
 [10 13]]
a @ b=
[[ 5  6]
 [10 13]]

Транспонировать матрицу можно с помощью `a.T` или `a.transpose()`. 

`.transpose()` предоставляет больше функциональности, позволяя переставлять размерности, а не только менять порядок на противоположный.

In [35]:
a = np.arange(40).reshape(5,2,4)
print(a.shape)
print(a.T.shape)
print(a.transpose().shape)
print(a.transpose(1, 2, 0).shape)   # перестановка размерностей

(5, 2, 4)
(4, 2, 5)
(4, 2, 5)
(2, 4, 5)

numpy поддерживает удобные функции для агрегации: max, argmax, sum, mean, prod и другие.

Функции можно вызвать как для конкретного объекта, так и из библиотеки.

In [36]:
print(f"a.max(): {a.max()}")
print(f"a.sum(): {a.sum()}")
print(f"np.sum(a): {np.sum(a)}")
# Это выдаст индекс, если матрицу развернуть в одномерный массив
print(f"a.argmax(): {a.argmax()}") 
# Это выдаст настоящее положение в матрице
print(f"координата в матрице a.argmax(): {np.unravel_index(a.argmax(), a.shape)}")

a.max(): 39
a.sum(): 780
np.sum(a): 780
a.argmax(): 39
координата в матрице a.argmax(): (np.int64(4), np.int64(1), np.int64(3))

Для всех операций можно указать параметр `axis` $-$ размерность по которой вычисляется операция. То есть после вычисления суммы указанная размерность `axis` пропадёт:

In [37]:
print(f"a.shape: {a.shape}")
print(f"a.max(axis=1): {a.max(axis=0)}")
print(f"shape: {a.max(axis=0).shape}")

a.shape: (5, 2, 4)
a.max(axis=1): [[32 33 34 35]
 [36 37 38 39]]
shape: (2, 4)

Можно передать несколько размерностей:

In [38]:
print(f"a.shape: {a.shape}")
print(f"a.max(axis=(0, 2)): {a.max(axis=(0, 2))}")
print(f"shape: {a.max(axis=(0, 2)).shape}")

a.shape: (5, 2, 4)
a.max(axis=(0, 2)): [35 39]
shape: (2,)

### Конкатенация многомерных массивов
Конкатенировать многомерные массивы позволяют функции `np.concatenate`, `np.vstack`, `np.hstack`, `np.dstack`.

In [39]:
x = np.arange(10).reshape(5, 2)
y = np.arange(100, 120).reshape(5, 4)
print(x)
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[100 101 102 103]
 [104 105 106 107]
 [108 109 110 111]
 [112 113 114 115]
 [116 117 118 119]]

Равносильные операции:

In [40]:
print(np.hstack([x, y]))
print(np.concatenate([x, y], axis=1))

[[  0   1 100 101 102 103]
 [  2   3 104 105 106 107]
 [  4   5 108 109 110 111]
 [  6   7 112 113 114 115]
 [  8   9 116 117 118 119]]
[[  0   1 100 101 102 103]
 [  2   3 104 105 106 107]
 [  4   5 108 109 110 111]
 [  6   7 112 113 114 115]
 [  8   9 116 117 118 119]]

In [41]:
p = np.array([1]).reshape([1,1,1,1])
print(np.vstack([p,p]).shape)   # конкатенация по первой размерности
print(np.hstack([p,p]).shape)   # конкатенация по второй размерности
print(np.dstack([p,p]).shape)   # конкатенация по третей размерности

(2, 1, 1, 1)
(1, 2, 1, 1)
(1, 1, 2, 1)

### Типы данных

В numpy поддерживаются разные типы данных.

In [42]:
x = [1, 11, 70000]

In [43]:
np.array(x, dtype=np.int32)

array([    1,    11, 70000], dtype=int32)

In [44]:
np.array(x, dtype=np.float32)

array([1.0e+00, 1.1e+01, 7.0e+04], dtype=float32)

In [45]:
np.array(x, dtype=np.float16)

C:\Users\Максим\AppData\Local\Temp\ipykernel_12144\1007038266.py:1: RuntimeWarning: overflow encountered in cast
  np.array(x, dtype=np.float16)

array([ 1., 11., inf], dtype=float16)

Некоторые типы данных недоступны, хоть для них и есть заготовки. Ваш процессор просто не способен оперировать 16-байтными числами.

In [46]:
try:
    np.array(x, dtype=np.float128)
except Exception as e:
    print(e)

module 'numpy' has no attribute 'float128'

In [47]:
np.array(x, dtype=np.str_)

array(['1', '11', '70000'], dtype='<U5')

Также в numpy есть возможность векторизовать функции. То есть сделать их применимыми к целому массиву.

In [48]:
def fun(x):
    return abs(x) * max(x, 5)

Просто так применить функцию к массиву не получится:

In [49]:
try:
    fun(np.arange(10))
except Exception as e:
    print(e)

The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

А если применить метод `np.vectorise`, то всё заработает:

In [50]:
f = np.vectorize(fun)
f(np.arange(10, dtype=np.float32))

array([ 0.,  5., 10., 15., 20., 25., 36., 49., 64., 81.], dtype=float32)

Но... Это работает долго. Это всё равно тот же самый цикл из Python, но просто чуть побыстрее.

In [51]:
from time import time
start = time()
f(np.arange(10000000, dtype=np.float32))
print(f"Время работы: {time() - start} сек.")

Время работы: 1.9378650188446045 сек.

А можно просто написать функцию, но с использованием элементов numpy. Тут вычисления уже идут в хорошо оптимизированном коде библиотеки.

In [52]:
def fun_np(x):
    return np.abs(x) * np.fmax(x, 5) # поэлементный максимум с заданным значением
print("Результат тот же:")
print(fun_np(np.arange(10, dtype=np.float32)))
print("Но быстрее:")
start = time()
fun_np(np.arange(10000000, dtype=np.float32))
print(f"Время работы: {time() - start} сек.")

Результат тот же:
[ 0.  5. 10. 15. 20. 25. 36. 49. 64. 81.]
Но быстрее:
Время работы: 0.040566444396972656 сек.

numpy также предоставляет множество операций линейной алгебры. Доступны они в [np.linalg](https://numpy.org/doc/stable/reference/routines.linalg.html).

Там есть векторные и скалярные произведения, сингулярные и собственные разложения матриц, есть возможность вычислить определитель, обратные матрицы, решить СЛАУ и другое.

## Pandas

Далее поговорим о популярной библиотеке pandas, служащей для загрузки табличных данных.

Основной метод создания таблиц - применение метода `pd.read_<file_extension>`, все виды поддерживаемых файлов можно увидеть [тут](https://pandas.pydata.org/pandas-docs/stable/reference/io.html), но нас чаще всего будет интересовать метод `read_csv`. 

Формат **csv** часть используется для хранения таблиц в обычных текстовых файлов. Большинство наборов табличных данных по машинному обучению записаны в формате **csv**.

In [53]:
import pandas as pd

df = pd.read_csv("titanic.csv", sep="\t") # sep - символ разделитель для столбцов таблицы

Можно отобразить несколько строк прочитанной матрицы. Это уже не просто матрица, как в numpy. Столбцы имеют осмысленное название. Есть индекс (Primary Key из SQL). Разные столбцы могут иметь разные типы, что невозможно в numpy.

In [54]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

В библиотеку встроены разные инструменты для обработки данных. Есть возможность получить разные статистические характеристики. С ними мы познакомимся на других занятиях, а пока познакомимся с основными элементами управления.

Сортировка:

In [55]:
df.sort_values("Age")

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

Но сам объект не поменялся:

In [56]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
151,152,1,1,"Pears, Mrs. Thomas (Edith Wearne)",female,22.0,1,0,113776,66.6000,C2,S
152,153,0,3,"Meo, Mr. Alfonzo",male,55.5,0,0,A.5. 11206,8.0500,NaN,S
153,154,0,3,"van Billiard, Mr. Austin Blyler",male,40.5,0,2,A/5. 851,14.5000,NaN,S
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
155,156,0,1,"Williams, Mr. Charles Duane",male,51.0,0,1,PC 17597,61.3792,NaN,C

Чтобы объект изменился надо передать параметр `inplace=True`. То есть работа метода происходит "на месте", не создавая копии.

In [57]:
df.sort_values("Age", inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
119,120,0,3,"Andersson, Miss. Ellis Anna Maria",female,2.00,4,2,347082,31.2750,NaN,S
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
121,122,0,3,"Moore, Mr. Leonard Charles",male,NaN,0,0,A4. 54510,8.0500,NaN,S
126,127,0,3,"McMahon, Mr. Martin",male,NaN,0,0,370372,7.7500,NaN,Q
128,129,1,3,"Peter, Miss. Anna",female,NaN,1,1,2668,22.3583,F E69,C
140,141,0,3,"Boulos, Mrs. Joseph (Sultana)",female,NaN,0,2,2678,15.2458,NaN,C
154,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S

Элемент в 78 строке

In [58]:
df.iloc[78]

PassengerId                              67
Survived                                  1
Pclass                                    2
Name           Nye, Mrs. (Elizabeth Ramell)
Sex                                  female
Age                                    29.0
SibSp                                     0
Parch                                     0
Ticket                           C.A. 29395
Fare                                   10.5
Cabin                                   F33
Embarked                                  S
Name: 66, dtype: object

Объект, у которого индекс 78, индексом (аналогом PK или UID из баз данных) может быть не только число.

In [59]:
df.loc[78]

PassengerId                               79
Survived                                   1
Pclass                                     2
Name           Caldwell, Master. Alden Gates
Sex                                     male
Age                                     0.83
SibSp                                      0
Parch                                      2
Ticket                                248738
Fare                                    29.0
Cabin                                    NaN
Embarked                                   S
Name: 78, dtype: object

ВЫборка по индексу и столбцам

In [60]:
df.loc[[78, 79, 100], ["Age", "Name"]]

       Age                           Name
78    0.83  Caldwell, Master. Alden Gates
79   30.00       Dowdell, Miss. Elizabeth
100  28.00        Petranec, Miss. Matilda

Если передать в [] имя одного столбца, то получим объект pd.Series. Это что-то вроде одномерного массива из numpy, но он  дополнительно имеет индекс.

In [61]:
df["Age"]

78     0.83
7      2.00
16     2.00
119    2.00
43     3.00
       ...
121     NaN
126     NaN
128     NaN
140     NaN
154     NaN
Name: Age, Length: 156, dtype: float64

А преобразовать в numpy можно с помощью свойства .values

In [62]:
type(df["Age"].values)

numpy.ndarray

Отдельно можно получить индекс

In [63]:
df["Age"].index

Index([ 78,   7,  16, 119,  43,  10,  63,  58,  50,  24,
       ...
        87,  95, 101, 107, 109, 121, 126, 128, 140, 154],
      dtype='int64', length=156)

Создаются они примерно так же, как np.array. Опционально указывается индекс

In [64]:
pd.Series([1, 2, 3], index=["Red", "Green", "Blue"])

Red      1
Green    2
Blue     3
dtype: int64

### SQL-подобные операции

Матрицы можно объединять с помощью join и megre

In [65]:
df1 = df[["Age", "Parch"]].copy()
df2 = df[["Ticket", "Fare"]].copy()

df1.join(df2) # объединение по индексу, возможно и по специфичному столбцу. Функционал полностью повторяет таковой в SQL

      Age  Parch         Ticket     Fare
78   0.83      2         248738  29.0000
7    2.00      1         349909  21.0750
16   2.00      1         382652  29.1250
119  2.00      2         347082  31.2750
43   3.00      2  SC/Paris 2123  41.5792
..    ...    ...            ...      ...
121   NaN      0      A4. 54510   8.0500
126   NaN      0         370372   7.7500
128   NaN      1           2668  22.3583
140   NaN      2           2678  15.2458
154   NaN      0      Fa 265302   7.3125

[156 rows x 4 columns]

In [66]:
df1 = df[["Age", "Parch", "PassengerId"]].copy()
df2 = df[["Ticket", "Fare", "PassengerId"]].copy()

In [67]:
pd.merge(df1, df2, on=["PassengerId"])

      Age  Parch  PassengerId         Ticket     Fare
0    0.83      2           79         248738  29.0000
1    2.00      1            8         349909  21.0750
2    2.00      1           17         382652  29.1250
3    2.00      2          120         347082  31.2750
4    3.00      2           44  SC/Paris 2123  41.5792
..    ...    ...          ...            ...      ...
151   NaN      0          122      A4. 54510   8.0500
152   NaN      0          127         370372   7.7500
153   NaN      1          129           2668  22.3583
154   NaN      2          141           2678  15.2458
155   NaN      0          155      Fa 265302   7.3125

[156 rows x 5 columns]

In [68]:
print("Pclass 1: ", df[df["Pclass"] == 1]["Age"].mean())
print("Pclass 2: ", df[df["Pclass"] == 2]["Age"].mean())
print("Pclass 3: ", df[df["Pclass"] == 3]["Age"].mean())

Pclass 1:  38.111111111111114
Pclass 2:  28.114827586206893
Pclass 3:  24.307142857142857

Средний возраст в каждом классе обслуживания:

In [69]:
df.groupby(["Pclass"])[["Age"]].mean()

              Age
Pclass
1       38.111111
2       28.114828
3       24.307143

Количество выживших в каждом классе:

In [70]:
df.groupby(["Survived"==1, "Pclass"]).count()

KeyError: False

Можно работать с строковыми столбцами:

In [ ]:
df["Name"].str.lower()

Имена людей:

In [ ]:
df["Name"].str.lower()\
          .str.replace(",", " ")\
          .str.split(".").str[1]

In [ ]:
df

Можно применить функцию поэлементно:

In [ ]:
df["Age"].apply(lambda x: 5 if x<1 else x*0.1)

# Matplotlib

Это библиотека для рисования графиков 

Мы сейчас познакомимся с основными возможностями библиотеки.

В библиотеке есть 2 основных объекта $-$ Рисунок (Figure) и график (Subplot или Axes). 
На каждом Рисунке можно разместить несколько Графиков. Рисунок соответствует непосредственно получаемому изображению, которое можно сохранить в файл или увидеть в ноутбуке или в отдельном окне, если вы запускали скрипт на питоне.

Основная часть библиотеки, позволяющая рисовать картинки это `matplotlib.pyplot`, которую традиционно импортируют с именем `plt`.

In [ ]:
import matplotlib.pyplot as plt

Для создания Рисунка необходимо вызвать метод `plt.figure()`. Для создания Графика необходимо вызвать метод `.add_subplot()`.

In [ ]:
fig = plt.figure()
ax = fig.add_subplot()
ax.plot([1, 4], [2, 5]) # Рисуем отрезок из точки (1,2) в точку (4,5)

Использованный выше метод `.plot(x,y)` позволяет рисовать ломанные, задаваемые списком координат по осям x и по y. Вместо списка можно передавать и numpy массивы и столбцы из pandas и другие совместимые контейнеры.

In [ ]:
fig = plt.figure()
ax = fig.add_subplot()
x = np.linspace(-10, 10, 100)
y = np.sin(x) # функция x^2 - x
ax.plot(x, y)

Как бы это странно не звучало, но ломанная не обязана быть функцией, то есть однозначным отображением x в y:

In [ ]:
fig = plt.figure()
ax = fig.add_subplot()
x = np.linspace(-10, 10, 41)
x1 = np.cos(x)
x2 = x
ax.plot(x1, x2)

В mtplotlib для лаконичности добавлена возможность вызывать методы для отрисовки не только от самого объекта, но и напрямую из библиотеки. На самом деле от наших глаз скрыто хранение последнего использованного изображения или графика в памяти библиотеки.

In [ ]:
x = np.linspace(-10, 10, 100)
y = np.square(x) - x
plt.plot(x, y)

x = np.linspace(-10, 10, 100)
y = 50 * np.exp(-x ** 2)
plt.plot(x, y)

Можно создать новое изображение, тогда ломанные будут нарисованы отдельно.

In [ ]:
x = np.linspace(-10, 10, 100)
y = np.square(x) - x
plt.plot(x, y)

plt.figure()    # Создание нового изображения
x = np.linspace(-10, 10, 100)
y = 50 * np.exp(-x ** 2)
plt.plot(x, y)

Часто нам потребуется рисовать облака точек. Это можно сделать с помощью метода `scatter`:

In [ ]:
x = np.linspace(-10, 10, 100)
y = np.sin(x)
plt.plot(x, y, linewidth = 6, color = "black")
plt.scatter(x, np.random.normal(y,0.3,size=y.shape))

Конечно, графики ещё можно всячески настраивать:

In [ ]:
x = np.linspace(-10, 10, 100)
y = np.square(x) - x
plt.plot(x, y,
         linewidth = 5, # Толщина линии
         color = "magenta", # цвет
         linestyle = "dashed", # стиль линии
         )
plt.scatter(x, y+ np.random.normal(0,10,size=y.shape),
            marker = "*",   # вид точек
            color = "green",  # цвет
            s= 150) # размер точек

plt.scatter(x, y+ np.random.normal(0,10,size=y.shape),
            marker = "s",  # вид точек
            color = "black",  # цвет
            alpha = 0.1,    # прозрачность
            s= 150,  # размер точек
            zorder = 100) # порядок отрисовки элементов, элемент с большим значением будет на переднем плане

Подписи к осям и картинкам тоже настраиваемы:

In [ ]:
x = np.linspace(-10, 10, 100)
y = np.square(x) - x
plt.plot(x, y,
         linewidth = 5, # Толщина линии
         color = "magenta", # цвет
         linestyle = "dashed", # стиль линии
         )
plt.xlabel("Ось Икс")
plt.ylabel("Latex текст: $\log_2(a^b)$")    # Поддерживаются формулы из latex
plt.title("Настройка подписей")
plt.ylim(-1, 150)   # настройка границ по y
plt.xlim(-7, 15)   # настройка границ по x

При вызове методов от объекта имена функций немного другие:

In [ ]:
x = np.linspace(-10, 15, 100)
y = np.square(x) - x
fig, axes = plt.subplots()
fig.set_size_inches(10,8)   # настройка размера изображения
axes.plot(x, y,
         linewidth = 5, # Толщина линии
         color = "magenta", # цвет
         linestyle = "dashed", # стиль линии
         )
axes.set_xlabel("Ось Икс")
axes.set_ylabel("Latex текст: $\log_2(a^b)$")    # Поддерживаются формулы из latex
axes.set_title("Настройка подписей")
axes.set_ylim(-1, 150)   # настройка границ по y
axes.set_xlim(-7, 15)   # настройка границ по x

Также на графиках можно изображать текст на указанных координатах. И, конечно, он тоже полностью настраиваем.

In [ ]:
x = np.linspace(-10, 15, 100)
y = np.square(x) - x
plt.plot(x, y)


plt.annotate("Текст на графике", xy=[5, 50])
plt.scatter([0], [10], marker="*")
plt.annotate("right top", xy=[0, 10], ha="right", va="top", fontsize=10)
plt.annotate("left bottom", xy=[0, 10], ha="left", va="bottom", fontsize=20, color="red")

Нарисуем гистограмму:

In [ ]:
x = np.random.normal(0,1,100)
fig, axes = plt.subplots(1, 2) # создание решётки из графиков с 1 строкой и 2 столбцами

# plt.gcf() даёт доступ к сохранённому в библиотеке объекту изображения
plt.gcf().set_size_inches(10,4)

axes[0].plot(x)
# plt.gca() даёт доступ к сохранённому в библиотеке объекту графика.
# Сохраняется последний созданный объект, а не тот с которым последним взаимодействовали
plt.gca().set_title("Последовательность") # это будет перезаписано далее, поскольку plt.gca() = axes[1]

axes[1].hist(x)

Доступно рисование тепловых карт и линий уровня.

`np.meshgrid(x,y)` полезный метод при рисовании двумерных графиков. Из координат x и y создаёт решётку точек с заданными координатами. Работает так: $x$ понимается как вектор-строка (1, n), a $y$ понимается как вектор-столбец (m, 1) далее размерности обоих векторов расширяются так, чтобы получились две матрицы размера (m, n).


$$x=\begin{pmatrix}x_1\\\vdots\\x_n\end{pmatrix} \;\;y=\begin{pmatrix}y_1\\\vdots\\y_m\end{pmatrix}$$

$$X, Y= np.meshgrid(x,y)$$

$$X = \begin{pmatrix}x_1&\dots&x_n\\\vdots&\ddots&\vdots\\x_1&\dots&x_n\end{pmatrix}\;\;
 Y = \begin{pmatrix}y_1&\dots&y_1\\\vdots&\ddots&\vdots\\y_m&\dots&y_m\end{pmatrix}$$

In [ ]:
def fun(x, y):
    return np.exp(-np.square(x) - np.square(y))

x = np.linspace(-2, 2, 50)
y = np.linspace(-2, 2, 100)

x, y = np.meshgrid(x, y)

plt.gcf().set_size_inches(10,6)

ax = plt.subplot(1,3,1)
plt.pcolormesh(x, y, fun(x, y))
plt.title("function")

ax = plt.subplot(1,3,2)
plt.pcolormesh(x, y, x, cmap="Blues")   # Можно менять градиент цветов
plt.title("x coordinate")

ax = plt.subplot(1,3,3)
plt.pcolormesh(x, y, y, cmap="rainbow_r",  # Можно менять градиент цветов
               vmin=0,  # Минимальное значение для назначения цвета
               vmax=1)  # Максимальное значение для назначения цвета
plt.title("y coordinate")

Линии уровня:

In [ ]:
def fun(x, y):
    return np.exp(-np.square(x) - np.square(y))

x = np.linspace(-2, 2, 100)
y = np.linspace(-2, 2, 100)

x, y = np.meshgrid(x, y)

plt.gcf().set_size_inches(10,6)

plt.contour(x, y, fun(x, y), levels=np.linspace(0,1,100)) # линии уровня

С базовыми возможностями мы познакомились, теперь вам необходимо выполнить задания:

# Домашнее задание:

**Блок Numpy.** Задания подразумевают, что писать циклы нельзя, необходимо использовать способности библиотеки numpy.

- Реализуйте функцию, возвращающую максимальный элемент в массиве `X` среди элементов, перед которыми стоит нулевой.

- Реализуйте функцию, принимающую на вход матрицу ```X``` и некоторое число ```value``` и возвращающую ближайший к числу элемент матрицы.

- Дана функция, обрабатывающая список объектов формы (p, k). А у вас есть матрица (n,m,k) Вычислите функцию относительно этой матрицы. Код функции менять нельзя, нужно преобразовать матрицу. Результат должен быть формы (n,m).

In [ ]:
def fun(x):
    # код этой функции изменять нельзя
    return np.sum(x, axis=1) + np.trace(x @ x.T)

data = np.random.normal(0, 5, size=(10,20,5))

# fun(data) не работает

- У вас есть массив точек в виде матрицы размерности (n, d), n $-$ количество точек, d $-$ размерность каждой точки. Вычислите попарные расстояние между всеми точками $-$ матрицу (n,n). Используется евклидово расстояние.  Попробуйте воспользоваться трюком с расширением размерности матрицы.

**Pandas:**

Загрузите данные о пассажирах Титаника из файла *titanic.csv* и ответьте на вопросы ниже.

- Опишите данный набор данных: какое распределение женщин/мужчин в нем? Сколько пассажиров ехало в каждом классе? Какой средний/минимальный/максимальный возраст пассажиров? Сколько было выживших пассажиров?

- Сгруппируйте записи по классам пассажиров, в каждой группе посчитайте средний возраст. Верно ли, что во всех классах эта величина примерно одинакова?

**Matplotlib:**

- Вам даны два набора точек в двумерном пространстве. Найдите центры масс этих наборов, соедините их прямой, постройте срединный перпендикуляр. Постройте проекции точек на срединный перпендикуляр. Подпишите координаты центров наборов точек.

In [ ]:
X1 = np.random.multivariate_normal([4,4],[[0.1,-0.4],[-0.4,3]], size = 10)
plt.scatter(X1[:,0], X1[:,1])

X2 = np.random.multivariate_normal([8,4],[[0.2,0.4],[0.4,1]], size = 10)
plt.scatter(X2[:,0], X2[:,1])

- Сравните три вида применения функции к массиву поэлементно: с помощью обычного python-цикла, при помощи np.vectorize и при помощи специальной реализации функции, используя средства numpy. Отобразите на графике зависимость времени работы от размера входного массива. Размер массива удобно взять возрастающим по экспоненте. Пример использования np.vectorize и реализации средствами numpy был приведён на занятии. Сделайте правильные подписи к осям картинки.